name: flutter_api_craft
description: "A comprehensive Flutter HTTP client with auth, retry, loading, snackbars, and GetX navigation support."
version: 0.0.5
homepage: "https://github.com/AnayatHossain/flutter_api_craft"
repository: "https://github.com/AnayatHossain/flutter_api_craft"
issue_tracker: "https://github.com/AnayatHossain/flutter_api_craft/issues"

topics:
  - http
  - networking
  - api
  - rest
  - getx

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.3.2
  connectivity_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http_mock_adapter: ^0.6.1
